gg.alert("💫𝑼𝒄𝒖𝒛 𝒇𝒊𝒚𝒂𝒕𝒕𝒂𝒏 𝑹𝒐𝒐𝒕-𝑹𝒐𝒎 𝑨𝒕𝒎𝒂𝒌 𝑰𝒔𝒕𝒊𝒚𝒐𝒓𝒔𝒂𝒏 @𝒆𝒒𝒆𝒙𝒉𝒆𝒍𝒍 (𝑷𝒄 𝑺𝒂𝒓𝒕𝒕𝒊𝒓)")
gg.alert(" 🌚BYPASS MAKER @FsmSassy FSM TEAM 🌝  \n ")
os.remove("src/main/java/com/google/errorprone/annotations/concurrent")
os.remove("third_party.java_src.error_prone.project.annotations.Google_internal")
os.remove("src/main/java/com/google/errorprone/annotations")
os.remove("src/main/java/com/google/errorprone/annotations/concurrent")
os.remove("third_party.java_src.error_prone.project.annotations.Google_internal")
os.remove("src/main/java/com/google/errorprone/annotations")
gg.clearResults()
os.remove("src/main/java/com/google/errorprone/annotations")
os.remove("src/main/java/com/google/errorprone/annotations/concurrent")
os.remove("third_party.java_src.error_prone.project.annotations.Google_internal")
gg.clearResults()
os.remove("src/main/java/com/google/errorprone/annotations")
os.remove("src/main/java/com/google/errorprone/annotations/concurrent")
os.remove("third_party.java_src.error_prone.project.annotations.Google_internal")
gg.setRanges(gg.REGION_C_ALLOC)
os.remove("src/main/java/com/google/errorprone/annotations")
os.remove("src/main/java/com/google/errorprone/annotations/concurrent")
os.remove("third_party.java_src.error_prone.project.annotations.Google_internal")
gg.searchNumber(":com.tencent.mobileqqa", gg.TYPE_BYTE)
os.remove("src/main/java/com/google/errorprone/annotations")
os.remove("src/main/java/com/google/errorprone/annotations/concurrent")
os.remove("third_party.java_src.error_prone.project.annotations.Google_internal")
gg.searchNumber(":com.tencent.mobileqqq", gg.TYPE_BYTE)
gg.clearResults()
os.remove("src/main/java/com/google/errorprone/annotations")
os.remove("src/main/java/com/google/errorprone/annotations/concurrent")
os.remove("third_party.java_src.error_prone.project.annotations.Google_internal")
gg.clearResults()
os.remove("src/main/java/com/google/errorprone/annotations")
os.remove("src/main/java/com/google/errorprone/annotations/concurrent")
os.remove("third_party.java_src.error_prone.project.annotations.Google_internal")
gg.setRanges(gg.REGION_C_ALLOC)
os.remove("src/main/java/com/google/errorprone/annotations")
os.remove("src/main/java/com/google/errorprone/annotations/concurrent")
os.remove("third_party.java_src.error_prone.project.annotations.Google_internal")
gg.searchNumber(":com.pubg.imobilex", gg.TYPE_BYTE)
os.remove("src/main/java/com/google/errorprone/annotations")
os.remove("src/main/java/com/google/errorprone/annotations/concurrent")
os.remove("third_party.java_src.error_prone.project.annotations.Google_internal")
gg.searchNumber(": ", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
os.remove("src/main/java/com/google/errorprone/annotations")
os.remove("src/main/java/com/google/errorprone/annotations/concurrent")
os.remove("third_party.java_src.error_prone.project.annotations.Google_internal")
gg.searchNumber(":com.tencent.mobileqqsa", gg.TYPE_BYTE)
os.remove("src/main/java/com/google/errorprone/annotations")
os.remove("src/main/java/com/google/errorprone/annotations/concurrent")
os.remove("third_party.java_src.error_prone.project.annotations.Google_internal")
gg.searchNumber(": ", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":/report", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.refineNumber(":/report", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.getResults(99999)
gg.clearResults()
gg.setVisible(false)
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":cheat", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.refineNumber(":cheat", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.getResults(99999)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":Cheat", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.refineNumber(":Cheat", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.getResults(99999)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":/tss", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.refineNumber(":/tss", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.getResults(99999)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":/report", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.refineNumber(":/report", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.getResults(99999)
gg.clearResults()
gg.setVisible(false)
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":cheat", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.refineNumber(":cheat", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.getResults(99999)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":Cheat", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.refineNumber(":Cheat", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.getResults(99999)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":/tss", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.refineNumber(":/tss", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.getResults(99999)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":tss_del_report_data", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.refineNumber(":tss_del_report_data", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(100, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll(":0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":tss_get_report_data", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.refineNumber(":tss_get_report_data", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(100, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll(":0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":tss_get_report_data2", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.refineNumber(":tss_get_report_data2", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(100, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll(":0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":tss_sdk_init", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.refineNumber(":tss_sdk_init", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(5000, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll(":0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":tss_sdk_rcv_anti_data", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.refineNumber(":tss_sdk_rcv_anti_data", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(100, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll(":0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":tss_sdk_setgamestatus", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.refineNumber(":tss_sdk_setgamestatus", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(100, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll(":0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":tss_sdk_setuserinfo_ex", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.refineNumber(":tss_sdk_setuserinfo_ex", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(100, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll(":0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":APPS_URL_HTTP", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.refineNumber(":APPS_URL_HTTP", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(5000, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll(":0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":APPS_URL_HTTPS_TEST", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.refineNumber(":APPS_URL_HTTPS_TEST", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(100, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll(":0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":ATM_REPORT_HOST_LIST", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.refineNumber(":ATM_REPORT_HOST_LIST", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(100, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll(":0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":ATM_REPORT_HOST_TEST_LIST", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.refineNumber(":ATM_REPORT_HOST_TEST_LIST", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(100, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll(":0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":tss_del_report_data", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.refineNumber(":tss_del_report_data", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(5000, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll(":0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":TssSDKGetReportData", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.refineNumber(":TssSDKGetReportData", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(100, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll(":0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":TssSDKDelReportData", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.refineNumber(":TssSDKDelReportData", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(100, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll(":0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":tss_get_report_data", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.refineNumber(":tss_get_report_data", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(100, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll(":0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":tss_enable_get_report_data", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.refineNumber(":tss_enable_get_report_data", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(5000, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll(":0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":tss_get_report_data2", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.refineNumber(":tss_get_report_data2", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(100, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll(":0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":tss_get_report_data3", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.refineNumber(":tss_get_report_data3", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(100, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll(":0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":tss_del_report_data3", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.refineNumber(":tss_del_report_data3", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(100, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll(":0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":tss", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.refineNumber(":tss", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(5000, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll(":0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":tss_sdk_rcv_anti_data", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.refineNumber(":tss_sdk_rcv_anti_data", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(100, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll(":0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":TssSDKInit", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.refineNumber(":TssSDKInit", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(100, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll(":0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":tss_del_report_data", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.refineNumber(":tss_del_report_data", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(100, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll(":0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":TssSDKSetUserInfo", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.refineNumber(":TssSDKSetUserInfo", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(5000, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll(":0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":TssSDKOnRecvData", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.refineNumber(":TssSDKOnRecvData", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(100, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll(":0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":TssSDKOnResume", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.refineNumber(":TssSDKOnResume", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(100, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll(":0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":TssSDKOnPause", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.refineNumber(":TssSDKOnPause", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(100, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll(":0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":TssSDKInit", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.refineNumber(":TssSDKInit", gg.TYPE_BYTE, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(5000, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll(":0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC | gg.REGION_CODE_APP)
gg.searchNumber(":kills", gg.TYPE_BYTE)
gg.refineNumber(":kills", gg.TYPE_BYTE)
gg.getResults(1000, nil, nil, nil, nil, nil, nil, nil, nil)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":ban", gg.TYPE_BYTE)
gg.refineNumber(":ban", gg.TYPE_BYTE)
gg.getResults(1000, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll(":Deactivated", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":AntiCheat", gg.TYPE_BYTE)
gg.refineNumber(":AntiCheat", gg.TYPE_BYTE)
gg.getResults(1000, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll(":Deactivated", gg.TYPE_BYTE)
gg.clearResults()
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC | gg.REGION_CODE_APP)
gg.setVisible(false)
gg.searchNumber(";CheatDetected", gg.TYPE_WORD, nil, nil, nil, nil)
gg.getResults(50000)
gg.editAll(";", gg.TYPE_WORD)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.setVisible(false)
gg.getResults(99999, nil, nil, nil, nil, nil, nil, nil, nil)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.setVisible(false)
gg.getResults(99999, nil, nil, nil, nil, nil, nil, nil, nil)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.setVisible(false)
gg.getResults(99999, nil, nil, nil, nil, nil, nil, nil, nil)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.setVisible(false)
gg.getResults(99999, nil, nil, nil, nil, nil, nil, nil, nil)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.setVisible(false)
gg.getResults(99999, nil, nil, nil, nil, nil, nil, nil, nil)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.setVisible(false)
gg.getResults(99999, nil, nil, nil, nil, nil, nil, nil, nil)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.setVisible(false)
gg.getResults(99999, nil, nil, nil, nil, nil, nil, nil, nil)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.setVisible(false)
gg.getResults(99999, nil, nil, nil, nil, nil, nil, nil, nil)
gg.clearResults()
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":libtprt.so", gg.TYPE_BYTE)
gg.getResults(200)
gg.editAll("0", gg.TYPE_DWORD)
gg.getResults(200)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":libtersafe.so", gg.TYPE_BYTE)
gg.getResults(200)
gg.editAll("0", gg.TYPE_DWORD)
gg.clearResults()
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":/data/user/0/com.tencent", gg.TYPE_BYTE)
gg.getResults(99999)
gg.editAll("116", gg.TYPE_BYTE)
gg.clearResults()
gg.setVisible(false)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":/data/user/0/com.pubg.imobile", gg.TYPE_BYTE)
gg.getResults(99999)
gg.editAll("116", gg.TYPE_BYTE)
gg.clearResults()
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.setVisible(false)
gg.searchNumber(":com.tencent.ig", gg.TYPE_BYTE)
gg.getResults(99999)
gg.editAll("116", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.setVisible(false)
gg.searchNumber(":com.pubg.krmobile", gg.TYPE_BYTE)
gg.getResults(99999)
gg.editAll("116", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.setVisible(false)
gg.searchNumber(":com.vng.pubgmobile", gg.TYPE_BYTE)
gg.getResults(99999)
gg.editAll("116", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.setVisible(false)
gg.searchNumber(":com.rekoo.pubgm", gg.TYPE_BYTE)
gg.getResults(99999)
gg.editAll("116", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.setVisible(false)
gg.searchNumber(":qos.hk.gcloudcs.com", gg.TYPE_BYTE)
gg.getResults(9999)
gg.editAll("116", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.setVisible(false)
gg.searchNumber(":cloud.gsdk.proximabeta.com", gg.TYPE_BYTE)
gg.getResults(9999)
gg.editAll("116", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.setVisible(false)
gg.searchNumber(":com.tencent.mobileqqu", gg.TYPE_BYTE)
gg.getResults(9999)
gg.editAll("116", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.setVisible(false)
gg.searchNumber(":com.tencent.mobileqqsa", gg.TYPE_BYTE)
gg.getResults(9999)
gg.editAll("116", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.setVisible(false)
gg.searchNumber(":com.tencent.mobileqq.plus", gg.TYPE_BYTE)
gg.getResults(9999)
gg.editAll("116", gg.TYPE_BYTE)
gg.clearResults()
gg.clearResults()
gg.setVisible(false)
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":com.tencent.mobileqqsa", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("119", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)gg.setVisible(false)
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PKHs/PufferFileList.json")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PKHs/puffer_temp")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PKHs/puffer_temp/")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs/ShadowTrackerExtra.log")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/cache/GCloud.ini")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/StatEventReportedFlag")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/StatEventReportedFlag/")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/cache")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/cache/")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/ProgramBinaryCache")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/tbslog")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PKHs/puffer_res.eifs")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PKHs/PufferFileList.json")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PKHs/puffer_temp")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PKHs/puffer_temp/")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs/ShadowTrackerExtra.log")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/cache/GCloud.ini")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/StatEventReportedFlag")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/StatEventReportedFlag/")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/cache")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/cache/")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/ProgramBinaryCache")
os.remove("/data/data/com.tencent.mobileqq.gg/data/data/user/0/com.tencent.iglite/databases")
os.remove("/sdcard/Android/data/com.tencent.iglite/cache/GCloud.ini")
os.remove("/sdcard/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs")
os.remove("/mnt/shell/0/emulated/Android/data/com.tencent.iglite/cache/GCloud.ini")
os.remove("/mnt/shell/0/emulated/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/cache/GCloud.ini")
os.remove("/sdcard/Android/data/com.tencent.iglite/cache/GCloud.ini")
os.remove("/sdcard/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs")
os.remove("/mnt/shell/0/emulated/Android/data/com.tencent.iglite/cache/GCloud.ini")
os.remove("/mnt/shell/0/emulated/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/cache/GCloud.ini")
os.remove("/sdcard/Android/data/com.tencent.iglite/cache/GCloud.ini")
os.remove("/sdcard/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs")
os.remove("/mnt/shell/0/emulated/Android/data/com.tencent.iglite/cache/GCloud.ini")
os.remove("/mnt/shell/0/emulated/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/cache/GCloud.ini")
os.remove("/sdcard/Android/data/com.tencent.iglite/cache/GCloud.ini")
os.remove("/sdcard/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs")
os.remove("/mnt/shell/0/emulated/Android/data/com.tencent.iglite/cache/GCloud.ini")
os.remove("/mnt/shell/0/emulated/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/cache/GCloud.ini")
os.remove("/sdcard/Android/data/com.tencent.iglite/cache/GCloud.ini")
os.remove("/sdcard/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/puffer-temp")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/apollo_reslist.flist")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/.")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/..")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/Puffer.")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/puffer-temp")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/apollo_reslist.flist")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/.")
gg.clearResults()
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("620137442967552;303473799200768", gg.TYPE_QWORD, false, gg.SIGN_FUZZY_EQUAL, 0, -1)
  gg.refineNumber("620137442967552", gg.TYPE_QWORD, false, gg.SIGN_FUZZY_EQUAL, 0, -1)
  gg.getResults(100000)
gg.editAll("361418272522109953", gg.TYPE_QWORD)
gg.clearResults()
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("578351706144768;564058054983680", gg.TYPE_QWORD, false, gg.SIGN_FUZZY_EQUAL, 0, -1)
  gg.refineNumber("578351706144768", gg.TYPE_QWORD, false, gg.SIGN_FUZZY_EQUAL, 0, -1)
  gg.getResults(100000)
gg.editAll("361418272522109953", gg.TYPE_QWORD)
gg.clearResults()
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("620137442967552;564058054983680", gg.TYPE_QWORD, false, gg.SIGN_FUZZY_EQUAL, 0, -1)
  gg.refineNumber("620137442967552", gg.TYPE_QWORD, false, gg.SIGN_FUZZY_EQUAL, 0, -1)
  gg.getResults(100000)
gg.editAll("361418272522109953", gg.TYPE_QWORD)
gg.clearResults()
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("566257078239232;576152682889216", gg.TYPE_QWORD, false, gg.SIGN_FUZZY_EQUAL, 0, -1)
  gg.refineNumber("566257078239232", gg.TYPE_QWORD, false, gg.SIGN_FUZZY_EQUAL, 0, -1)
  gg.getResults(100000)
gg.editAll("361418272522109953", gg.TYPE_QWORD)
gg.clearResults()
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("581650241028096;573953659633664", gg.TYPE_QWORD, false, gg.SIGN_FUZZY_EQUAL, 0, -1)
  gg.refineNumber("581650241028096", gg.TYPE_QWORD, false, gg.SIGN_FUZZY_EQUAL, 0, -1)
  gg.getResults(100000)
gg.editAll("361418272522109953", gg.TYPE_QWORD)
gg.clearResults()
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("577252194516992;575053171261440", gg.TYPE_QWORD, false, gg.SIGN_FUZZY_EQUAL, 0, -1)
  gg.refineNumber("577252194516992", gg.TYPE_QWORD, false, gg.SIGN_FUZZY_EQUAL, 0, -1)
  gg.getResults(100000)
gg.editAll("361418272522109953", gg.TYPE_QWORD)
gg.clearResults()
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("573953659633664;577252194516992", gg.TYPE_QWORD, false, gg.SIGN_FUZZY_EQUAL, 0, -1)
  gg.refineNumber("573953659633664", gg.TYPE_QWORD, false, gg.SIGN_FUZZY_EQUAL, 0, -1)
  gg.getResults(100000)
gg.editAll("361418272522109953", gg.TYPE_QWORD)
gg.clearResults()
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("578351706144768;303473799200768", gg.TYPE_QWORD, false, gg.SIGN_FUZZY_EQUAL, 0, -1)
  gg.refineNumber("578351706144768", gg.TYPE_QWORD, false, gg.SIGN_FUZZY_EQUAL, 0, -1)
  gg.getResults(100000)
gg.editAll("361418272522109953", gg.TYPE_QWORD)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC) 
gg.searchNumber("131330;262403", gg.TYPE_DWORD) 
gg.getResults(37) 
gg.editAll("131330", gg.TYPE_DWORD) 
gg.clearResults() 
gg.setRanges(gg.REGION_C_ALLOC) 
gg.searchNumber("", gg.TYPE_DWORD) 
gg.getResults(37) 
gg.editAll("131330", gg.TYPE_DWORD) 
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC | gg.REGION_OTHER)
gg.searchNumber("7,37553829e-40;4,091231e-41", gg.TYPE_FLOAT)
gg.getResults(99999)
gg.editAll("4,34822913e-42", gg.TYPE_FLOAT)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC | gg.REGION_OTHER)
gg.searchNumber("1,07899982e-41;2,56852403e-40", gg.TYPE_FLOAT)
gg.getResults(99999)
gg.editAll("4,34822913e-42", gg.TYPE_FLOAT)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC | gg.REGION_OTHER)
gg.searchNumber("2,05194937e-40;1,52109547e-40", gg.TYPE_FLOAT)
gg.getResults(99999)
gg.editAll("4,34822913e-42", gg.TYPE_FLOAT)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC | gg.REGION_OTHER)
gg.searchNumber("1,52102541e-40;1,09879736e-39", gg.TYPE_FLOAT)
gg.getResults(99999)
gg.editAll("4,34822913e-42", gg.TYPE_FLOAT)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC | gg.REGION_OTHER)
gg.searchNumber("2,46474387e-40;3,58732407e-40", gg.TYPE_FLOAT)
gg.getResults(99999)
gg.editAll("4,34822913e-42", gg.TYPE_FLOAT)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC | gg.REGION_OTHER)
gg.searchNumber("4,04650155e-40;2,65461981e-40", gg.TYPE_FLOAT)
gg.getResults(99999)
gg.editAll("4,34822913e-42", gg.TYPE_FLOAT)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC | gg.REGION_OTHER)
gg.searchNumber("3,74516633e-40;6,1558481e-40", gg.TYPE_FLOAT)
gg.getResults(99999)
gg.editAll("4,34822913e-42", gg.TYPE_FLOAT)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC | gg.REGION_OTHER)
gg.searchNumber("1,11207046e-40;1,86540852e-40", gg.TYPE_FLOAT)
gg.getResults(99999)
gg.editAll("4,34822913e-42", gg.TYPE_FLOAT)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC | gg.REGION_OTHER)
gg.searchNumber("5,65384694e-40;1,46741173e-40", gg.TYPE_FLOAT)
gg.getResults(99999)
gg.editAll("4,34822913e-42", gg.TYPE_FLOAT)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC | gg.REGION_OTHER)
gg.searchNumber("1,53929834e-40;1,4260454e-40", gg.TYPE_FLOAT)
gg.getResults(99999)
gg.editAll("4,34822913e-42", gg.TYPE_FLOAT)
gg.toast("😉")
gg.clearResults() 
gg.setRanges(gg.REGION_C_ALLOC) 
gg.searchNumber("131330;262403", gg.TYPE_DWORD) 
gg.getResults(37) 
gg.editAll("131330", gg.TYPE_DWORD)
gg.clearResults() 
gg.setRanges(gg.REGION_C_ALLOC)
    gg.searchNumber("65793;524425", gg.TYPE_DWORD)
    gg.refineNumber("65793", gg.TYPE_DWORD)
    gg.getResults(50000)
    gg.editAll("84149249", gg.TYPE_DWORD)
    gg.clearResults()
    gg.setRanges(gg.REGION_C_ALLOC)
    gg.searchNumber("525313;131844", gg.TYPE_DWORD)
    gg.refineNumber("525313", gg.TYPE_DWORD)
    gg.getResults(50000)
    gg.editAll("84149249", gg.TYPE_DWORD)
    gg.clearResults()
    gg.setRanges(gg.REGION_C_ALLOC)
    gg.searchNumber("132104;132620", gg.TYPE_DWORD)
    gg.refineNumber("132104", gg.TYPE_DWORD)
    gg.getResults(50000)
    gg.editAll("84149249", gg.TYPE_DWORD)
    gg.clearResults()
    gg.setRanges(gg.REGION_C_ALLOC)
    gg.searchNumber("134024;135040", gg.TYPE_DWORD)--decci pro ya adam 🤣
    gg.refineNumber("134024", gg.TYPE_DWORD)
    gg.getResults(50000)
    gg.editAll("84149249", gg.TYPE_DWORD)
    gg.clearResults()
    gg.setRanges(gg.REGION_C_ALLOC)
    gg.searchNumber("135436;135936", gg.TYPE_DWORD)
    gg.refineNumber("135436", gg.TYPE_DWORD)
    gg.getResults(50000)
    gg.editAll("84149249", gg.TYPE_DWORD)
    gg.clearResults()
    gg.setRanges(gg.REGION_C_ALLOC)
    gg.searchNumber("144140;66304", gg.TYPE_DWORD)
    gg.refineNumber("144140", gg.TYPE_DWORD)
    gg.getResults(50000)
    gg.editAll("84149249", gg.TYPE_DWORD)
    gg.clearResults()
    gg.setRanges(gg.REGION_C_ALLOC)
    gg.searchNumber("796673;196736", gg.TYPE_DWORD)--Sassy
    gg.refineNumber("796673", gg.TYPE_DWORD)
    gg.getResults(50000)
    gg.editAll("84149249", gg.TYPE_DWORD)
    gg.clearResults()
    gg.setRanges(gg.REGION_C_ALLOC)
    gg.searchNumber("264192;133509", gg.TYPE_DWORD)
    gg.refineNumber("264192", gg.TYPE_DWORD)
    gg.getResults(50000)
    gg.editAll("84149249", gg.TYPE_DWORD)
    gg.clearResults() 
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("144116287587484160;1099511628032", gg.TYPE_QWORD)
gg.refineNumber("144116287587484160", gg.TYPE_QWORD)
gg.getResults(100000)
gg.editAll("300647710720", gg.TYPE_QWORD)
gg.setVisible(false)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("72341268037894400;281474976713984", gg.TYPE_QWORD)
gg.refineNumber("72341268037894400", gg.TYPE_QWORD)
gg.getResults(100000)
gg.editAll("300647710720", gg.TYPE_QWORD)
gg.setVisible(false)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("1103806595328;2203318223104", gg.TYPE_QWORD)
gg.refineNumber("1103806595328", gg.TYPE_QWORD)
gg.getResults(100000)
gg.editAll("300647710720", gg.TYPE_QWORD)
gg.setVisible(false)
gg.clearResults() 
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("17180069123;17180200195")
gg.getResults(5000)
gg.editAll("580550729400320", gg.TYPE_QWORD)
gg.setVisible(false)
gg.clearResults() 
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("17179870465;17180069123")
gg.getResults(5000)
gg.editAll("580550729400320", gg.TYPE_QWORD)
gg.setVisible(false)
gg.clearResults() 
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("17180134659;17180004866")
gg.getResults(5000)
gg.editAll("580550729400320", gg.TYPE_QWORD)
gg.setVisible(false)
gg.clearResults() 
gg.setRanges(gg.REGION_C_ALLOC) 
gg.searchNumber("144387;70658", gg.TYPE_DWORD) 
gg.getResults(37) 
gg.editAll("131330", gg.TYPE_DWORD) 
gg.clearResults() 
gg.setRanges(gg.REGION_C_ALLOC) 
gg.searchNumber("131330;262403", gg.TYPE_DWORD) 
gg.getResults(37) 
gg.editAll("131330", gg.TYPE_DWORD) 
gg.clearResults() 
gg.setRanges(gg.REGION_C_ALLOC) 
gg.searchNumber("9729;10497", gg.TYPE_DWORD) 
gg.getResults(37) 
gg.editAll("1048320", gg.TYPE_DWORD) 
gg.clearResults() 
gg.setRanges(gg.REGION_C_ALLOC) 
gg.searchNumber("28416;13568", gg.TYPE_DWORD) 
gg.getResults(37) 
gg.editAll("1048320", gg.TYPE_DWORD) 
gg.clearResults() 
gg.setRanges(gg.REGION_C_ALLOC) 
gg.searchNumber("788736;41216", gg.TYPE_DWORD) 
gg.getResults(37) 
gg.editAll("1048320", gg.TYPE_DWORD) 
gg.clearResults() 
gg.setRanges(gg.REGION_C_ALLOC) 
gg.searchNumber("11776", gg.TYPE_DWORD) 
gg.getResults(37) 
gg.editAll("1048320", gg.TYPE_DWORD) 
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("144115188075987456;144115188076118528", gg.TYPE_QWORD)
gg.getResults(100000)
gg.editAll("578351706144768", gg.TYPE_QWORD)
gg.setVisible(false)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("144115273975923200;144115188076708352", gg.TYPE_QWORD)
gg.getResults(100000)
gg.editAll("578351706144768", gg.TYPE_QWORD)
gg.setVisible(false)
gg.clearResults() 
gg.setRanges(gg.REGION_C_ALLOC) 
gg.searchNumber("17671;16658", gg.TYPE_DWORD) 
gg.getResults(5000) 
gg.editAll("18188", gg.TYPE_DWORD) 
gg.clearResults() 
gg.setRanges(gg.REGION_C_ALLOC) 
gg.searchNumber("10271;12043", gg.TYPE_DWORD) 
gg.getResults(5000) 
gg.editAll("18188", gg.TYPE_DWORD) 
gg.clearResults() 
gg.setRanges(gg.REGION_C_ALLOC) 
gg.searchNumber("15376;18188;17546", gg.TYPE_DWORD) 
gg.getResults(5000) 
gg.editAll("18188", gg.TYPE_DWORD) 
gg.clearResults()
gg.setRanges(gg.REGION_ANONYMOUS)
gg.searchNumber(";Alive", gg.TYPE_WORD)
gg.getResults(100000)
gg.editAll(";VİP", gg.TYPE_WORD)
gg.clearResults()
gg.setRanges(gg.REGION_ANONYMOUS)
gg.searchNumber(";Killed", gg.TYPE_WORD)
gg.getResults(100000)
gg.editAll(";Sassy", gg.TYPE_WORD)
gg.clearResults()
gg.clearResults()
gg.setRanges(gg.REGION_ANONYMOUS)
gg.searchNumber(";Kalan", gg.TYPE_WORD)
gg.getResults(100000)
gg.editAll(";Sassy", gg.TYPE_WORD)
gg.clearResults()
gg.setRanges(gg.REGION_ANONYMOUS)
gg.searchNumber(";Les‌", gg.TYPE_WORD)
gg.getResults(100000)
gg.editAll(";VİP", gg.TYPE_WORD)
gg.clearResults()
gg.searchNumber(";Leş", gg.TYPE_WORD)
gg.getResults(100000)
gg.editAll(";VİP", gg.TYPE_WORD)
gg.clearResults()
gg.alert("💎Bypass Aktif #NOBANSEX Sassy 😉")
